apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-capture-client
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      app: image-capture-client
  template:
    metadata:
      labels:
        app: image-capture-client
    spec:
      hostNetwork: true
      nodeSelector:
        {{- toYaml .Values.client.nodeSelector | nindent 8 }}
      containers:
        - name: image-capture-client
          image: "{{ .Values.image.repository }}/{{ .Values.image.clientTag }}"
          imagePullPolicy: Always  # Force Kubernetes à vérifier les nouvelles versions de l'image
          env:
            - name: API_URL
              value: "{{ .Values.client.apiUrl }}"
          volumeMounts:
            - name: video-device0
              mountPath: /dev/video0
              readOnly: true
            - name: video-device1
              mountPath: /dev/video1
              readOnly: true
            - name: video-device2
              mountPath: /dev/video2
              readOnly: true
            - name: video-device3
              mountPath: /dev/video3
              readOnly: true
          securityContext:
            privileged: true  # Donne l'accès aux périphériques pour le conteneur
      volumes:
        - name: video-device0
          hostPath:
            path: /dev/video0
            type: CharDevice  # Type de périphérique spécial pour la caméra
        - name: video-device1
          hostPath:
            path: /dev/video1
            type: CharDevice  # Type de périphérique spécial pour la caméra
        - name: video-device2
          hostPath:
            path: /dev/video2
            type: CharDevice  # Type de périphérique spécial pour la caméra
        - name: video-device3
          hostPath:
            path: /dev/video3
            type: CharDevice  # Type de périphérique spécial pour la caméra
