apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    args:
      - sleep
      - "4000"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always